#!/usr/bin/env python3
"""
sync_offline_nlu.py — generate the on-device FAQ table from backend/nlu.py
==========================================================================
The server's grounded FAQ answers (DigiLocker validity, receipts, contesting,
compounding, seizure, towing, Good Samaritan, …) are the single source of
truth. This writes them into the mobile/PWA offline engine so airplane-mode
answers match the server word for word.

Run after editing backend/nlu.py:
    python3 scripts/sync_offline_nlu.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
OUT = ROOT / "apps" / "mobile" / "src" / "offline" / "faq.generated.ts"


def main() -> None:
    import nlu
    lines = [
        "// AUTO-GENERATED by scripts/sync_offline_nlu.py from backend/nlu.py — do not edit.",
        "/* eslint-disable */",
        "export const FAQ: [RegExp, string][] = [",
    ]
    for rx, answer in nlu._FAQ:
        lines.append(f"  [new RegExp({json.dumps(rx.pattern)}, 'i'), {json.dumps(answer, ensure_ascii=False)}],")
    lines += ["];", "",
              f"export const UNSAFE_RE = new RegExp({json.dumps(nlu.UNSAFE_RE.pattern)}, 'i');",
              f"export const UNSAFE_REPLY = {json.dumps(nlu.UNSAFE_REPLY, ensure_ascii=False)};",
              f"export const IDENTITY_REPLY = {json.dumps(nlu.smalltalk_reply('who are you'), ensure_ascii=False)};",
              f"export const CAPABILITY_REPLY = {json.dumps(nlu.smalltalk_reply('what can you do'), ensure_ascii=False)};",
              ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(nlu._FAQ)} FAQ entries)")


if __name__ == "__main__":
    main()
