/**
 * graph.ts — on-device port of backend/graph_engine.py (offline slice)
 * ────────────────────────────────────────────────────────────────────
 * Loads the compiled offline bundle and provides the exact traversal +
 * fine-cascade logic the server uses, so offline answers are identical to
 * online rule-based answers. No network, no model.
 *
 * Faithful ports of: _norm, violations_by_keyword, get_fine (city→state→
 * central cascade), quick_fine (fine_card builder).
 */

// The bundle is generated by scripts/build_offline_bundle.py
import bundle from './drivelegal_offline.json';

export interface Violation {
  name: string;
  mv_section: string | null;
  grp: string | null;
  compoundable: boolean;
  vehicle_applicability: string[];
  keywords: string[];
  tips_to_avoid: string | null;
  what_to_do_next: string | null;
  consequence: string | null;
  dl_consequence: string | null;
  common_misconception: string | null;
}

export interface FineNode {
  first_offence: number | null;
  repeat_offence: number | null;
  imprisonment: string | null;
  vehicle_class: string | null;
  state_code: string | null;
  city_code: string | null;
  note: string | null;
}

export interface FineCard {
  violation_code: string;
  violation_name: string;
  mv_section: string | null;
  compoundable: boolean;
  what_to_do_next: string | null;
  tips_to_avoid: string | null;
  licence_consequence: string | null;
  fine_first: number | null;
  fine_repeat: number | null;
  imprisonment: string | null;
  fine_source: string;
  state_code: string | null;
  city_code: string | null;
  violation_group: string | null;
}

type Bundle = {
  violations: Record<string, Violation>;
  states: Record<string, { name: string; multiplier: number; fallback_central: boolean }>;
  fines: Record<string, FineNode>;
  fine_by_violation: Record<string, {
    central: string[];
    state: Record<string, string[]>;
    city: Record<string, string[]>;
  }>;
  keyword_to_vio: Record<string, string[]>;
  vio_by_bucket: Record<string, string[]>;
};

const B = bundle as unknown as Bundle;

/** Faithful port of graph_engine._norm */
export function norm(text: string): string {
  if (!text) return '';
  let t = text.toLowerCase().trim();
  t = t.replace(/[^a-z0-9& ]+/g, ' ');
  t = t.replace(/\s+/g, ' ').trim();
  return t;
}

// Faithful port of graph_engine._violations_by_keyword: start from the
// precomputed keyword_to_vio index (normalised keys), then augment with each
// violation's keywords + name + common_misconception. Must match exactly so
// offline resolver scores == server resolver scores.
let _kwByNorm: Record<string, string[]> | null = null;
export function violationsByKeyword(): Record<string, string[]> {
  if (_kwByNorm) return _kwByNorm;
  const out: Record<string, string[]> = {};
  for (const [k, v] of Object.entries(B.keyword_to_vio)) {
    out[norm(k)] = v.slice(); // last collision wins — same as the Python dict comp
  }
  for (const [vcode, node] of Object.entries(B.violations)) {
    const extras: string[] = [...(node.keywords || [])];
    if (node.name) extras.push(node.name);
    if (node.common_misconception) extras.push(node.common_misconception);
    for (const raw of extras) {
      const key = norm(raw);
      if (!key) continue;
      const bucket = (out[key] = out[key] || []);
      if (!bucket.includes(vcode)) bucket.push(vcode);
    }
  }
  _kwByNorm = out;
  return out;
}

export function getViolation(code: string): Violation | null {
  return B.violations[code] ?? null;
}

export function getState(code: string) {
  return B.states[code] ?? null;
}

export function vioByBucket(bucket: string): string[] {
  return B.vio_by_bucket[bucket] ?? [];
}

/** Faithful port of graph_engine.get_fine — city → state → central cascade. */
export function getFine(
  violationCode: string,
  stateCode?: string | null,
  cityCode?: string | null,
  vehicleClass?: string | null,
): (FineNode & { fine_source: string }) | null {
  const fbi = B.fine_by_violation[violationCode];
  if (!fbi) return null;

  const pick = (nids: string[] | undefined, vc?: string | null): FineNode | null => {
    if (!nids || nids.length === 0) return null;
    if (vc) {
      for (const nid of nids) {
        const n = B.fines[nid];
        if (n && n.vehicle_class === vc) return n;
      }
    }
    for (const nid of nids) {
      const n = B.fines[nid];
      if (n && !n.vehicle_class) return n;
    }
    return B.fines[nids[0]] ?? null;
  };

  if (cityCode) {
    const r = pick(fbi.city?.[cityCode], vehicleClass);
    if (r) return { ...r, fine_source: 'city' };
  }
  if (stateCode) {
    const r = pick(fbi.state?.[stateCode], vehicleClass);
    if (r) return { ...r, fine_source: 'state' };
  }
  const r = pick(fbi.central, vehicleClass);
  if (r) return { ...r, fine_source: 'central' };
  return null;
}

/** Faithful port of graph_engine.quick_fine (base graph; no patch overlay offline). */
export function quickFine(
  violationCode: string,
  stateCode?: string | null,
  cityCode?: string | null,
  vehicleFineClass?: string | null,
): FineCard | null {
  const fine = getFine(violationCode, stateCode, cityCode, vehicleFineClass);
  if (!fine) return null;
  const vio = getViolation(violationCode);
  return {
    violation_code: violationCode,
    violation_name: vio ? vio.name : violationCode,
    mv_section: vio ? vio.mv_section : null,
    compoundable: vio ? vio.compoundable : false,
    what_to_do_next: vio ? vio.what_to_do_next : null,
    tips_to_avoid: vio ? vio.tips_to_avoid : null,
    licence_consequence: vio ? (vio.dl_consequence || vio.consequence) : null,
    fine_first: fine.first_offence,
    fine_repeat: fine.repeat_offence,
    imprisonment: fine.imprisonment,
    fine_source: fine.fine_source || 'central',
    state_code: fine.state_code,
    city_code: fine.city_code,
    violation_group: vio ? vio.grp : null,
  };
}
